shell_project/shell_app/urls.py
from django.urls import path
from .views import Shell

app_name = 'shell_app'

urlpatterns = [
    path('', Shell.as_view(), name='shell'),
]

shell_project/shell_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shell/', include('shell_app.urls')),
]

shell_project/shell_app/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    username = models.CharField(max_length=150)

    created_by = models.DateTimeField(auto_now_add=True)
    updated_by = models.DateTimeField(auto_now=True)

    def get_full_name(self):
        return self.first_name+" "+self.last_name
    
    def __str__(self):
        return self.username

class DailyTemperature(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    temperature = models.FloatField()

    created_by = models.DateTimeField(auto_now_add=True)
    updated_by = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.temperature)

shell_project/shell_app/forms.py
from django import forms

class ShellForm(forms.Form):

    code = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'codearea'}),
    )

    error_css_class = 'error'

shell_project/shell_app/views.py
from django.views.generic import FormView
from .forms import ShellForm
from django.http import (
    HttpResponseForbidden,
    HttpResponseNotFound
)
from django.conf import settings
try:
    # Only for python 2
    from StringIO import StringIO
except ImportError:
    # For python 3
    from io import StringIO

from shell_project.settings import (
    ADMIN_SHELL_SESSION_KEY,
    ADMIN_SHELL_OUTPUT_SIZE,
    ADMIN_SHELL_ENABLE,
    ADMIN_SHELL_ONLY_DEBUG_MODE,
    # ADMIN_SHELL_ONLY_FOR_SUPERUSER,
)

import django
import sys
import traceback


def run_code(code):
    """
    Execute code and return result with status = success|error
    Function manipulate stdout to grab output from exec
    """
    status = "success"
    out = ""
    tmp_stdout = sys.stdout
    buf = StringIO()

    try:
        sys.stdout = buf
        exec(code)
    except Exception:
        out = traceback.format_exc()
        status = 'error'
    else:
        out = buf.getvalue()
    finally:
        sys.stdout = tmp_stdout

    result = {
        'code': code,
        'out':  out,
        'status': status,
    }
    return result


def get_py_version():
    ver = sys.version_info
    return "{0}.{1}.{2}".format(ver.major, ver.minor, ver.micro)


class Shell(FormView):

    template_name = "shell_app/shell.html"
    form_class = ShellForm
    success_url = "."

    # Output - list ran code and results
    # store in session
    output = None

    def dispatch(self, request, *args, **kwargs):
        """Override to check settings"""
        if django.VERSION < (1, 10):
            is_auth = request.user.is_authenticated()
        else:
            is_auth = request.user.is_authenticated

        if not ADMIN_SHELL_ENABLE:
            return HttpResponseNotFound("Not found: Django admin shell is not enabled")
        # elif is_auth is False or request.user.is_staff is False:
        #     return HttpResponseForbidden("Forbidden: To access Django admin shell you must have access the admin site")
        elif ADMIN_SHELL_ONLY_DEBUG_MODE and settings.DEBUG is False:
            return HttpResponseForbidden("Forbidden :Django admin shell require DEBUG mode")
        # elif ADMIN_SHELL_ONLY_FOR_SUPERUSER and request.user.is_superuser is False:
        #     return HttpResponseForbidden("Forbidden: To access Django admin shell you must be superuser")
        return super(Shell, self).dispatch(request, *args, **kwargs)

    def get_output(self):
        if self.output is None:
            output = self.request.session.get(ADMIN_SHELL_SESSION_KEY, [])
            self.output = output[:ADMIN_SHELL_OUTPUT_SIZE]
        return self.output

    def add_to_outout(self, item):
        output = self.get_output()
        output[:0] = [item]
        self.output = output
        return self.output

    def save_output(self):
        output = self.get_output()
        self.request.session[ADMIN_SHELL_SESSION_KEY] = output

    def clear_output(self):
        self.output = []
        self.save_output()

    def get(self, request, *args, **kwargs):
        # Clear output history - set empty list and save
        if request.GET.get("clear_history", "no") == "yes":
            self.clear_output()
        return super(Shell, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        code = form.cleaned_data.get("code", "")
        if len(code.strip()) > 0:
            result = run_code(code)
            self.add_to_outout(result)
            self.save_output()
        return super(Shell, self).form_valid(form)

    def get_context_data(self, **kwargs):
        """Add output to context"""
        ctx = super(Shell, self).get_context_data(**kwargs)
        ctx['site_header'] = "Djang admin shell"
        ctx['has_permission'] = True
        ctx['output'] = self.get_output()
        ctx['python_version'] = get_py_version()
        return ctx

shell_project/shell_app/templates/shell_app/base.html
<html>
    <head>
        <title>
        {% block title %}Title{% endblock %}
        </title>
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <meta name="robots" content="NONE,NOARCHIVE">

        {# Add bootstrap style #}
        {% block extrastyle %}
        {% endblock extrastyle %}

    </head>

    <body>
        <div id="container">

        <div id="content" class="colM">
        {% block header %}
        {% endblock header %}
        {% block content %}
        {% endblock content %}
        </div>

        {# footer #}
        {% block footer %}
        {% endblock %}

        {# Add jQuery style #}
        {% block extrahead %}
        {% endblock %}
        </div>
    </body>
</html>

shell_project/shell_app/templates/shell_app/shell.html
{% extends "shell_app/base.html" %}
{% load static %}
{% block title %}Django Shell{% endblock %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static "shell_app/css/bootstrap3.min.css" %}"/>
    <link rel="stylesheet" href="{% static "shell_app/css/base.css" %}"/>
    <link rel="stylesheet" href="{% static "shell_app/js/linedtextarea/jquery-linedtextarea.css" %}"/>
    <link rel="stylesheet" href="{% static "shell_app/css/shell.css" %}"/>
{% endblock extrastyle %}

{% block header %}
    
        <nav class="navbar navbar-dark bg-primary">
            <a class="navbar-brand" style="color: aliceblue;" href="#">Django Shell</a>
        </nav>
  
{% endblock header %}

{% block content %}

    <div class="row">
        <div class="col-xs-4">
            <h5>
                <span class="glyphicon glyphicon-list"></span>
                Output ({{ output|length }}):
            </h5>
        </div>
        <div class="col-xs-4 text-info">
            <h5> Python version : {{python_version}} </h5>
        </div>
        <div class="col-xs-4 text-right">
            <a class="btn btn-danger btn-sm" id="clear-history" href="{% url "shell_app:shell" %}?clear_history=yes">
                <span class="glyphicon glyphicon-trash"></span>
                Clear history
            </a>
        </div>
    </div>

    <div id="output_container">
        {% for result in output reversed %}
            <div class="output">
                <div class="code"><pre>{{ result.code }}</pre></div>
                <div class="out"><pre class="{{ result.status }}">{{ result.out }}</pre></div>
            </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col-xs-12">

            <form id="shell_form" class="form form-horizontal" method="post" action=".">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                <div style="width:100%">
                    {{ form.code }}
                    {% if form.code.errors %}
                        {{ form.code.errors }}
                    {% endif %}
                </div>

                <button id="run_code" type="submit" class="btn btn-success btn-block">
                    <span class="glyphicon glyphicon-play-circle"></span>
                    Run code (ctrl + enter)
                </button>

            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-6 text-danger">
            Be careful, in production environment `admin shell` is highly dangerous.<br/>
            Blocking command like <code>input</code> not work.<br/>
            This code: <code> os.system('vim') </code> will run `vim` in background.<br/>
        </div>
        <div class="col-xs-6 text-info">
            <span class="glyphicon glyphicon-info-sign"></span> Ctrl + Enter : Run code<br/>
            <span class="glyphicon glyphicon-info-sign"></span> Ctrl + Up/Down : Load code from history<br/>
            <span class="glyphicon glyphicon-info-sign"></span> Tab : Indent = 4 spaces
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h1>Data Visualization</h1>
        </div>
    </div>

{% endblock %}

{# Add jQuery style #}
{% block extrahead %}
    <script src="{% static "shell_app/js/jquery.min.js" %}"></script>
    <script src="{% static "shell_app/js/linedtextarea/jquery-linedtextarea.js" %}"></script>
    <script src="{% static "shell_app/js/shell.min.js" %}"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="{% static "shell_app/js/visualization.js" %}"></script>
{% endblock %}